### ISSUE TITLE
安装之后在主入口配置跑不起来报错

### ISSUE THREAD

**Issue by mizhicangyue** [surely-vue/table#157]
**控制台报错：**
```
runtime-core.esm-bundler.js:2252 Uncaught TypeError: isFunction is not a function
    at defineComponent (runtime-core.esm-bundler.js:2252:10)
    at StyleContext.js:98:42
```
// main.js
```
import 'ant-design-vue/dist/reset.css';
import '@surely-vue/table/dist/index.less';
import STable from '@surely-vue/table';
import { createApp } from 'vue'
import App from './App.vue'

const app = createApp(App)

app.use(STable);
app.mount('#app')
```
// vite.config.js
```
 css:{
    preprocessorOptions: {
      less:{
        javascriptEnabled: true,
      }
    },
  }
```
不配置javascriptEnabled:true就会报另一个错
![image](https://github.com/surely-vue/table/assets/45323549/3aa30e80-2493-4a00-a264-c4b3b72ff2e7)

**Comment by tangjinzhou** [comment]
如要使用 less ，是需要配置 javascriptEnabled 的。

第一个问题提供的信息有限，无法定位问题，你可以提供一个最小复现的示例(压缩包上传即可)
