### ISSUE TITLE
无意中发现的bug ，帮每一行的每一个单元格都设置rowDrag = true; 然后左右滚动，表格的数据就会消失

### ISSUE THREAD

**Issue by chenbaicheng** [surely-vue/table#23]
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (runtime-core.esm-bundler.js:1085:29)
    at updateComponent (runtime-core.esm-bundler.js:4947:13)
    at processComponent (runtime-core.esm-bundler.js:4901:13)
    at patch (runtime-core.esm-bundler.js:4489:21)
    at patchKeyedChildren (runtime-core.esm-bundler.js:5262:17)
    at patchChildren (runtime-core.esm-bundler.js:5205:21)
    at processFragment (runtime-core.esm-bundler.js:4886:17)
    at patch (runtime-core.esm-bundler.js:4482:17)
    at patchKeyedChildren (runtime-core.esm-bundler.js:5262:17)
    at patchChildren (runtime-core.esm-bundler.js:5181:17)

**Comment by tangjinzhou** [comment]
什么版本，并没有复现
是否可以提供复现示例

**Comment by chenbaicheng** [comment]
发了邮件谢谢你   
	const {
		data,
		run,
		loading,
		current,
		pageSize,
		totalPage,
	} = usePagination(queryData, {
		formatResult: res => {
			createColumns(res);
			//createEditModal(res.data.results[0]);
			//console.log(JSON.stringify(res.data));

			return res.data;
		},
		pagination: {
			currentKey: 'page',
			pageSizeKey: 'results',
			//totalKey: 'data.value.total',

		},
	});

这里的totalKey: 'data.value.total',  也不行  

	const list = computed(() => {
			if (data.value === undefined) {
				return [];
				console.log('dataSource is undefined');
			} else {
				console.log('dataSource no undefined');
				return data.value.results;
			}
		}
	);
但是我获取数据的data.value.results 又可以。

**Comment by tangjinzhou** [comment]
升级最新版本
